#!/bin/bash
#Provided by Wyatt S Carpenter
(cd ..; rm vdisk1; make clean; make)

for i in $( find .  -name "*.txt" -not -name "*.*.txt" ); do
    echo $i: $(./run-test $i 2>/dev/null && echo PASS || echo FAIL)
done
